version: '2.3'
services:
  python:
    build:
      context: ./Docker
      dockerfile: Dockerfile-pytorch
    runtime: nvidia
    command: /bin/bash
    # command: jupyter notebook --port 9999  --allow-root --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - "7000:7000"
      - "9999:9999"
      - "5000:5000"
    tty: true
    volumes:
      - ./Project:/Project
      - ./Data:/Data
      - ./artifact:/artifact
      - ./mlruns:/mlruns
  tensorboard:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    runtime: nvidia
    command: /bin/bash
    tty: true
    ports:
      - "3333:3333"
    
